FROM gradle:7.6.0-jdk17-alpine

ENV GRADLE_USER_HOME=/opt/gradle-home
ARG APP_HOME=/opt/app
ARG ENTRY_POINT=./k8s/entrypoint.sh

WORKDIR $APP_HOME

VOLUME ["$APP_HOME", "$GRADLE_USER_HOME"]

COPY $ENTRY_POINT /opt/entrypoint.sh

ENTRYPOINT /opt/entrypoint.sh